on: push
name: publish on release
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Publish to NPM 
    - uses: actions/checkout@master
      uses: actions/npm@master
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      with:
        args: publish
